manifest:
  remotes:
    - name: KyleDThompson
      url-base: https://github.com/KyleDThompson
  projects:
    - name: zmk
      remote: KyleDThompson
      revision: default_rebound
      import: app/west.yml
  self:
    path: config
